### ISSUE TITLE
App crashes not stable

### ISSUE THREAD

**Issue by lineez82** [imshyam/mintube#35]
I have successfully downloaded and installed properly on my phone and it runs too.  Issue is when I try to play a video app crashes.

**Comment by imshyam** [comment]
@lineez82, May I know little details, Like, What android version, What device?

**Comment by cstubens** [comment]
@imshyam I've been using mintube on multiple devices. Its very useful! Thanks for the great app! Rock on.

Anyway, I just upgraded to a Note8 and now I have crashes. (sm-n950w running android 7.1.1)

It occurs when I attempt to play a video through the Mintube app, or when I attempt to share a video to Mintube from the YouTube app.

Error message is a popup saying "Mintube keeps stopping" with a button to "close app".

Happy to provide crashlogs but I'll need instructions on how to get them.

Cheers

**Comment by Aarowaim** [comment]
Encountered this issue.

When videos are selected, the player crashes repeatedly and attempts to retry opening the video until it must exit. "Mintube keeps stopping" was the error message.

The problem was fixed on my S8 Edge by uninstalling Mintube (which had been installed on a previous version of Android), then reinstalling. It seems to occur when the device has received a software update since mintube was installed.

**Comment by imshyam** [comment]
Hi all,

Fixed the issue. Please check [here](http://bit.ly/mintube).

**Comment by imshyam** [comment]
Hi all,

Fixed the issue. Please check [here](http://bit.ly/mintube).

**Comment by cstubens** [comment]
It works for me. Thank you sir!
