### ISSUE TITLE
Youtube API

### ISSUE THREAD

**Issue by icss91** [imshyam/mintube#8]
Any possibility of using youtube api instead of the web?

**Comment by imshyam** [comment]
I am using YouTube API's. 

What you meant I suppose is Can we use YouTube Android API? 
And the answer is if you want all the features then NO. Because I tried using YouTube Android API and there were problems like If you decrease the size of the player after a prespecified(by YouTube) constant than the video will pause, If anything is above/override the player(like you made your custom play-pause button in the center of the player or facebook messenger chat head is over the player window) then the video will pause, you can not hide the player as it will also pause the video etc.

So If you want none of the above and some more, fewer features then you can use Android API's. 

I'm using  YouTube IFRAME API's btw.
